version: '3'
volumes:
    dados:
networks: 
    banco:
    web:
    fila:
services: 
    db:
        image: postgres:9.6
        container_name: "db"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=db
        volumes:
       # Volume dos dados
        - dados:/var/lib/postgresql/data
        # Scripts
        - ./scripts:/scripts
        - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks: 
            - banco
    frontend:
        image: nginx:1.13
        container_name: "frontend"
        volumes: 
        #Site
        - ./web:/usr/share/nginx/html/
        #Configuracao do proxy reverso
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        networks: 
            - web
        depends_on: 
            - app
    app:
        image: python:3.6
        container_name: "app"
        #APP
        volumes:
        - ./app:/app 
        working_dir: /app
        command: bash ./app.sh
        networks: 
            - banco
            - web
            - fila
        depends_on: 
            - db
            - queue
    queue:
        image: redis:3.2
        container_name: "queue" 
        networks: 
            - fila
    worker:
        image: python:3.6
        container_name: "worker"
        volumes: 
            - ./worker:/worker
        working_dir: /worker
        command: bash ./app.sh 
        networks: 
            - fila
        depends_on: 
            - queue
            - app
        
     